# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squiddle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='length_in_minutes',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeblock',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
