# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 03:19
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields
import squiddle_app.rest_data


class Migration(migrations.Migration):

    dependencies = [
        ('squiddle_app', '0002_auto_20170403_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='parent_schedule',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='json',
            field=jsonfield.fields.JSONField(default={'blocks': {squiddle_app.rest_data.Day(0): [], squiddle_app.rest_data.Day(1): [], squiddle_app.rest_data.Day(2): [], squiddle_app.rest_data.Day(3): [], squiddle_app.rest_data.Day(4): [], squiddle_app.rest_data.Day(5): [], squiddle_app.rest_data.Day(6): []}, 'days': []}),
        ),
        migrations.DeleteModel(
            name='TimeBlock',
        ),
    ]
